name: shared_utils
description: Shared utilities for personal Flutter projects
version: 0.0.1
author: Quabynah Bilson <codelbas.quabynah@gmail.com>
homepage: https://github.com/Quabynah-Codelabs/private-packages/tree/main/shared_utils

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.0.0-nullsafety
  feather_icons: ^1.1.0-nullsafety.0
  fluttericon: ^2.0.0
  flutter_svg: ^0.21.0-nullsafety.0
  google_fonts: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

flutter:
